mode: rule
log-level: info
unified-delay: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - system
  nameserver:
    - tls://dns.google#手动选择兜底国家
  direct-nameserver:
    - system
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  use-system-hosts: false
profile:
  store-selected: true
proxy-groups:
  - name: "手动选择兜底国家"
    type: select
    proxies:
      - "港台日新韩-节点组"
      - "香港-节点组"
      - "台湾-节点组"
      - "日本-节点组"
      - "新加坡-节点组"
      - "韩国-节点组"
      - "美国-节点组"
      - "手动节点"
  - name: "GPT-节点组"
    type: url-test
    include-all: true
    proxies:
      - "手动节点"
    url: "https://chatgpt.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 1000
    filter: "(^(?!.*游戏)(?!.*H01)(?!.*美国-IEPL).*美国.*)"
  - name: "Claude-节点组"
    type: url-test
    include-all: true
    proxies:
      - "手动节点"
    url: "https://claude.ai/generate_204"
    interval: 5
    tolerance: 20
    timeout: 1000
    filter: "(^(?!.*游戏)(?!.*H01)(?!.*美国-IEPL).*美国.*)"
  - name: "谷歌-节点组"
    type: url-test
    include-all: true
    proxies:
      - "手动节点"
    url: "https://www.google.com.hk/generate_204"
    interval: 5
    tolerance: 20
    timeout: 150
    filter: "(^(?!.*游戏).*香港.*)"
  - name: "CloudFlare-节点组"
    type: url-test
    include-all: true
    proxies:
      - "手动节点"
    url: "http://dash.cloudflare.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 150
    filter: "(^(?!.*游戏).*(香港|澳门|台湾|新加坡|日本|韩国).*)"
  - name: "GitHub-节点组"
    type: url-test
    include-all: true
    proxies:
      - "手动节点"
    url: "http://github.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 150
    filter: "(^(?!.*游戏).*(香港|澳门|台湾|新加坡|日本|韩国).*)"
  - name: "手动节点"
    type: select
    include-all: true
  - name: "港台日新韩-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 150
    filter: "(^(?!.*游戏)(?!.*25x).*(香港|台湾|新加坡|日本|韩国).*)"
  - name: "香港-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 150
    filter: "(^(?!.*游戏).*香港.*)"
  - name: "台湾-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 150
    filter: "(^(?!.*游戏).*台湾.*)"
  - name: "日本-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 150
    filter: "(^(?!.*游戏)(?!.*25x).*日本.*)"
  - name: "新加坡-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 150
    filter: "(^(?!.*游戏).*新加坡.*)"
  - name: "韩国-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 300
    filter: "(^(?!.*游戏).*韩国.*)"
  - name: "美国-节点组"
    type: url-test
    include-all: true
    url: "http://www.gstatic.com/generate_204"
    interval: 5
    tolerance: 20
    timeout: 300
    filter: "(^(?!.*游戏).*美国.*)"
rule-providers:
  Claude:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.yaml"
    path: ./rules/Claude.yaml
    interval: 86400
rules:
  - DOMAIN,cvb.9563067.xyz,手动选择兜底国家
  - DOMAIN,cvw.9563067.xyz,手动选择兜底国家
  - DOMAIN-SUFFIX,9563067.xyz,DIRECT
  - DOMAIN-KEYWORD,epic,DIRECT
  - DOMAIN-REGEX,^dl.*mypikpak\.com$,DIRECT
  - DOMAIN,zeze.teracloud.jp,DIRECT
  - GEOSITE,category-games@CN,DIRECT
  - GEOSITE,openai,GPT-节点组
  - RULE-SET,Claude,Claude-节点组
  - GEOSITE,google,谷歌-节点组
  - GEOSITE,cloudflare,CloudFlare-节点组
  - GEOSITE,github,GitHub-节点组
  - GEOSITE,geolocation-!cn,手动选择兜底国家
  - GEOSITE,CN,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - PROCESS-NAME,firefox.exe,手动选择兜底国家
  - PROCESS-NAME,Telegram.exe,手动选择兜底国家
  - MATCH,DIRECT
